INSERT INTO `stage` (`name`) VALUES 
('3D Land'),
('75m'),
('Arena Ferox'),
('Balloon Fight'),
('Battlefield'),
('Big Battlefield'),
('Big Blue'),
('Boxing Ring'),
('Bridge of Eldin'),
('Brinstar'),
('Brinstar Depths'),
('Castle Siege'),
('Coliseum'),
('Corneria'),
('Delfino Plaza'),
('Distant Planet'),
('Dracula\'s Castle'),
('Dream Land'),
('Dream Land (3DS)'),
('Duck Hunt'),
('Final Destination'),
('Find Mii'),
('Flat Zone X'),
('Fountain of Dreams'),
('Fourside'),
('Frigate Orpheon'),
('Gamer'),
('Garden of Hope'),
('Gaur Plain'),
('Gerudo Valley'),
('Golden Plains'),
('Great Bay'),
('Great Plateau Tower'),
('Green Greens'),
('Green Hill Zone'),
('Halberd'),
('Hanenbow'),
('Hyrule Castle'),
('Jungle Japes'),
('Kalos Pokémon League'),
('Kongo Falls'),
('Kongo Jungle'),
('Living Room'),
('Luigi\'s Mansion'),
('Lylat Cruise'),
('Magicant'),
('Mario Bros'),
('Mario Circuit (SSB4)'),
('Mario Circuit (SSBB)'),
('Mario Galaxy'),
('Midgar'),
('Moray Towers'),
('Mushroom Kingdom (SSB)'),
('Mushroom Kingdom II'),
('Mushroom Kingdom U'),
('Mushroomy Kingdom'),
('Mute City (3DS)'),
('New Donk City Hall'),
('New Pork City'),
('Norfair'),
('Onett'),
('Pac-Land'),
('Palutena\'s Temple'),
('Paper Mario'),
('Peach\'s Castle'),
('PictoChat 2'),
('Pilotwings'),
('Pirate Ship'),
('Pokémon Stadium'),
('Pokémon Stadium 2'),
('Port Town Aero Dive'),
('Princess Peach\'s Castle'),
('Prism Tower'),
('Rainbow Cruise'),
('Reset Bomb Forest'),
('Saffron City'),
('Shadow Moses Island 2'),
('Skyloft'),
('Skyworld'),
('Smashville'),
('Spear Pillar'),
('Spirit Train'),
('Summit'),
('Super Mario Maker'),
('Suzaku Castle'),
('Temple'),
('The Great Cave Offensive'),
('Tomodachi Life'),
('Tortimer Island'),
('Town and City'),
('Umbra Clock Tower'),
('Unova Pokémon League'),
('Venom'),
('WarioWare, Inc.'),
('Wii Fit Studio'),
('Wily Castle'),
('Windy Hill Zone'),
('Wrecking Crew'),
('Wuhu Island'),
('Yoshi\'s Island (SSB)'),
('Yoshi\'s Island (SSBB)'),
('Yoshi\'s Island (SSBM)'),
('Yoshi\'s Story');